import "dotenv/config";

export const {
  PORT,
  JWT_SECRET,
  FE_PORT,
  NODEMAILER_EMAIL,
  NODEMAILER_PASS,
  CLOUDINARY_NAME,
  CLOUDINARY_KEY,
  CLOUDINARY_SECRET,
  GOOGLE_ID,
  GOOGLE_SECRET,
  FACEBOOK_ID,
  FACEBOOK_SECRET,
  OPENCAGE_KEY,
} = process.env;
