import "dotenv/config";

export const {
  PORT,
  JWT_SECRET,
  FE_PORT,
  NODEMAILER_EMAIL,
  NODEMAILER_PASS,
  CLOUDINARY_NAME,
  CLOUDINARY_KEY,
  CLOUDINARY_SECRET,
  GOOGLE_ID,
  GOOGLE_SECRET,
  OPENCAGE_KEY,
  MIDTRANS_CLIENT_KEY,
  MIDTRANS_SERVER_KEY,
  DEFAULT_STORE_ID,
} = process.env;
